import type { Metadata } from 'next'
import './globals.css'
import { Inter as FontSans } from 'next/font/google'
// import localFont from 'next/font/local'
import { ThemeProvider } from '@/components/theme-provider'

import { cn } from '@/lib/utils'
import { Header } from '@/components/header'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

// const creditFont = localFont({
//   src: '../fonts/creditcard-font.ttf',
//   display: 'swap',
//   variable: '--font-credit-card',
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'font-sans antialiased',
          fontSans.variable
          // creditFont.variable
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <footer></footer>
        </ThemeProvider>
      </body>
    </html>
  )
}
